# Generated by Django 3.1.8 on 2023-04-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30)),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('streetaddress2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('postalcode', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('confirmpassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone_number', models.IntegerField()),
                ('Age', models.IntegerField(blank=True)),
                ('Gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address1', models.CharField(blank=True, max_length=50)),
                ('Address2', models.CharField(blank=True, max_length=50)),
                ('PostalCode', models.CharField(blank=True, max_length=50)),
                ('Password', models.CharField(max_length=500)),
            ],
        ),
    ]
